// <auto-generated />
namespace BlogApp4.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UserN : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserN));
        
        string IMigrationMetadata.Id
        {
            get { return "201602150348264_UserN"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
